name: Robocode-kernel
on:
    push:
        branches:
            - robocode

jobs:
    build:
        name: Package
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
                python: ['3.7', '3.8']
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: '2.5'
            - uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - name: What
              run: rake what
            - name: Setup
              run: rake envsetup
            - name: Packaging
              run: rake package
            - uses: actions/upload-artifact@v1
              with:
                  name: ${{ matrix.os }}-${{ matrix.python }}-artifacts
                  path: ./dist/

